services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file: .env
    depends_on:
      - db
    networks:
      - db

  db:
    container_name: postgres-db
    image: postgres
    env_file: .env
    volumes:
      - db:/data/postgres
    ports:
      - "5600:5432"
    expose:
      - 5600
    networks:
      - db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    networks:
      - db

networks:
  db:
    driver: bridge

volumes:
  db:
