services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file: .env
    depends_on:
      - database
    networks:
      - database

  database:
    container_name: postgres-database
    image: postgres
    env_file: .env
    volumes:
      - database:/data/postgres
    ports:
      - "5600:5432"
    expose:
      - 5600
    networks:
      - database
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    networks:
      - database

networks:
  database:
    driver: bridge

volumes:
  database:
